//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714SEngstrom2H
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CateringModelContainer : DbContext
    {
        public CateringModelContainer()
            : base("name=CateringModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Caterer> Caterers { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmpStatus> EmpStatus { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
    }
}
